---
title: Intraclass correlation coefficient in Linear Mixed Effects Models
author: null
date: '2020-01-10'
slug: intraclass-correlation-coefficient-in-linear-mixed-effects-models
categories: [LMM, ICC, correlation]
tags: [R, stats]
editor_options: 
  chunk_output_type: console
---

```{r, echo=TRUE}
if (!requireNamespace("pacman")){
  install.packages("pacman")
}

pacman::p_load(sjstats)
pacman::p_load(sjPlot)
pacman::p_load(lme4)
pacman::p_load(MASS)
```


# Simulate Data

100 participants will be ranking 20 items based on importance simulated from a multivariate normal distribution. 

```{r}
n.participants <- 100
n.items <- 20

Sigma <- 0.9 ^ toeplitz(1:n.items)
diag(Sigma) <- 1

# Subject needs to be a factor for lmer
DT <- data.frame(Subject_ID = factor(rep(1:n.participants, each = n.items)),
                 Item = rep(1:n.items, n.participants),
                 Importance = as.vector(replicate(n.participants, mvrnorm(1, mu = rep(0,n.items), Sigma = Sigma))))

head(DT)
str(DT)
```




# Calculate ICC

```{r}
fit0 <- lme4::lmer(Importance ~ 1 + (1 | Subject_ID), data = DT)
sjPlot::tab_model(fit0)
performance::icc(fit0)
```

