#!/bin/sh

#DIR=$(dirname "$0")

#cd $DIR/..

SRC_BRANCH="master"


# Check if there are any uncommitted changes
if ! git diff-index --quiet HEAD --; then
    echo "Changes to the following files are uncommitted:"
    git diff-index --name-only HEAD --
    echo "Please commit the changes before proceeding."
    # Push to SRC_BRANCH
    git add -fA
    git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
    git push -f -q origin $SRC_BRANCH
    echo "Aborting."
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

#DEPLOY_BRANCH="master"

echo "Deleting old publication"
rm -rf public
mkdir public
git worktree prune
rm -rf .git/worktrees/public/

echo "Checking out gh-pages branch into public"
git worktree add -B gh-pages public origin/gh-pages

echo "Removing existing files"
rm -rf public/*

echo "Generating site"
Rscript -e "blogdown::build_site()"

echo "Updating gh-pages branch"
cd public && git add --all && git commit -m "Publishing to gh-pages (publish_to_ghpages.sh)" && git push origin gh-pages